export const ACTION_TYPES = {
  SET_CONVERSATION: 'SET_CONVERSATION',
  ADD_MESSAGE: 'ADD_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
  SET_ACTIVE: 'SET_ACTIVE'
} as const;

export type ActionType = typeof ACTION_TYPES[keyof typeof ACTION_TYPES]; 